### ISSUE TITLE
Wisp in a Bottle Crashes my Game

### ISSUE THREAD

**Issue by Antiiilluminati** [Some-Bunny/Planetside#10]
Used the item in a random room in the Hallow, first time using it and it crashed my game

Here's the output log, dunno if it will help

[LogOutput.log](https://github.com/user-attachments/files/15523350/LogOutput.log)

**Comment by Antiiilluminati** [comment]
I tried this item again after I found it and it didn't crash my game, mustve been a one-off thing

**Comment by Some-Bunny** [comment]
guh
