### ISSUE TITLE
What are the unlocking conditions for netherite chamber

### ISSUE THREAD

**Issue by 59160153** [Some-Bunny/Planetside#17]
I used the command to lock everything out of curiosity, and as a result, the diamond chamber did not turn into a netherite chamber，
And the netherite chamber was unlocked in a confused way, and there was no way to unlock it
![image](https://github.com/user-attachments/assets/23a7ade8-9776-4943-9504-0a6bf2e26389)
![image](https://github.com/user-attachments/assets/fa579864-ca5b-4af8-b789-41fa3ff30b7b)

**Comment by Some-Bunny** [comment]
the netherite chamber does not have a standard unlock condition, and should be considered more an easter egg than an actual unlock.

the diamond chamber simply turns into the netherite chamber once you pick it up and have every other item and gun unlocked.
