### ISSUE TITLE
Severe framerate, audio, and gameplay issues with the Shamber enemy

### ISSUE THREAD

**Issue by PlasmaPerson** [Some-Bunny/Planetside#18]
Often, when the Shamber enemy is in the room, my game will completely bug out with various effects:
- Player and enemy bullets will move extremely slowly, sometimes even staying completely still.
- A very loud and constant sound will play. It appears to be the sound of either an enemy dying, or a bullet hitting an enemy, and it plays multiple times a second without stopping.
- The Shamber will sometimes not despawn upon clearing the room, resulting in a softlock.
- Even when the Shamber does despawn upon clearing the room, the other effects do not go away, and the framerate will go down to less than 1 fps.

I have a very high suspicion it's caused by the Shamber stealing a bullet from a companion, such as Baby Good Mimic, Super Space Turtle, or any other companion from both the base game and ones that are modded in.

**Comment by Some-Bunny** [comment]
This is a bug related to Shambers not properly checking their projectile lists properly, causing an infinite loop with the game not being able to finish executing code properly.

 This should be fixed for next patch.
