### ISSUE TITLE
Spinning Death causes persistent lag.

### ISSUE THREAD

**Issue by Hitmanforrent** [Some-Bunny/Planetside#2]
The Spinning Death passive item seems to cause persistent slowdown, even after its projectiles are despawned. The lag seems to go away upon entering a boss room or moving to the next floor. I was playing with https://enter-the-gungeon.thunderstore.io/package/ApacheThunder/TheGarbageCollector/ enabled so it might be a consequence of that, but doing a manual collection didn't seem to fix the issue.

**Comment by Some-Bunny** [comment]
should be fixed since a while ago I forgot this page existed lol
