### ISSUE TITLE
Door Lord Softlock

### ISSUE THREAD

**Issue by DeathW1ng39** [Some-Bunny/Planetside#3]
Hello, I've met Door Lord in Gungeon Proper, and after he died he refused to disappear, thus softlocking the game. I don't really know if it's caused by this mod in particular, but on the floor prior to this (Oubliette) Blobulord's health bar also refused to go away (and it did before I've installed this mod). 

Here's a video of the aforementioned softlock.

https://github.com/Some-Bunny/Planetside/assets/124525666/be610678-a91b-4147-b251-2eae2a201c16

**Comment by Some-Bunny** [comment]
i cant really help you if you dont provide an output log, as you have items from multiple different mods
