### ISSUE TITLE
Infinite enemy death glitch

### ISSUE THREAD

**Issue by DeathW1ng39** [Some-Bunny/Planetside#4]
Hello again, I was hoping that I won't go onto this thread again, but here we are. 

https://github.com/Some-Bunny/Planetside/assets/124525666/31e3b63c-5008-4478-85e0-9714d28a886f

As you can see, I can take damage, but everything apart from beam weapons refuses to move. Now I'm not a time wizard, and didn't use any commands to do that, so that's most likely a bug.

**Comment by DeathW1ng39** [comment]
Here's console log
![изображение](https://github.com/Some-Bunny/Planetside/assets/124525666/603c6e15-4fd8-458e-a362-cb63b3569746)


> Hello again, I was hoping that I won't go onto this thread again, but here we are.
> 2023-06-07.23-30-27.mp4
> 
> As you can see, I can take damage, but everything apart from beam weapons refuses to move. Now I'm not a time wizard, and didn't use any commands to do that, so that's most likely a bug.

**Comment by DeathW1ng39** [comment]
Damn it's hard to add new comments in github, here's the console log I wanted to send
![изображение](https://github.com/Some-Bunny/Planetside/assets/124525666/2d8d8ec5-8681-4a86-8371-861369c2864a)

**Comment by DeathW1ng39** [comment]
So I gave myself an Escape Rope with the console, and it fixed it, but without the console that would've been another softlock.

**Comment by Some-Bunny** [comment]
okay I can take a look and fix that one, thank you
