### ISSUE TITLE
Another softlock

### ISSUE THREAD

**Issue by DeathW1ng39** [Some-Bunny/Planetside#5]
Here I am again. I don't know if I'm lucky or something but I got another issue. 

So basically prior to this softlock I picked up the Blank Bullets and used the one-use item to spawn the mech boss (I don't remember its name) and in a couple of rooms I've tried to backtrack, and the room that I've cleared before (in which I fought with the mini boss of bullethell), became closed once again and the time stop  (from the issue #4) repeated. 

As before, I used the escape rope to quit the room, but as soon as I entered it... Well you can see what happened on the video.

https://github.com/Some-Bunny/Planetside/assets/124525666/ccaa364e-a8da-4845-b48e-5b6d27ea81ff

As you can see I can't move, shoot, open ammonomicon, use blanks, dodgeroll, etc.

![изображение](https://github.com/Some-Bunny/Planetside/assets/124525666/517d665e-a25c-4510-abeb-0c4b96b3fa63)

Here's the log (it's filled with identical errors).

**Comment by Some-Bunny** [comment]
im going to need more information than that for these bug reports, i need a list of items that you had in your inventory as well with these bug reports, and, preferably, a *full* output log file, which you can find here
![image](https://github.com/Some-Bunny/Planetside/assets/70037543/bf8e8e29-6cce-49e9-a700-275c0e519526)

**Comment by DeathW1ng39** [comment]
Here you go. It's around the line 4642.
[LogOutput.log](https://github.com/Some-Bunny/Planetside/files/11729160/LogOutput.log)

**Comment by Some-Bunny** [comment]
an item list would also be preferable, though I can already see you had a different modded item so you cant just shift the blame outright onto me unless you provide a proper item list

**Comment by DeathW1ng39** [comment]
So I don't know how to get an item list, but what I can say for sure after experimenting a little, is that the other mod, called "Oddments" was the one at fault. So in the end, looks like this issue was somehow fixed (by uninstalling the mod in question).
