### ISSUE TITLE
Black screen upon re-entering the Breach

### ISSUE THREAD

**Issue by Lordfortress** [Some-Bunny/Planetside#7]
Since around ver1.3.148 there have been repeated reports in the Mod The Gungeon discord of getting a black screen upon reentering the breach after a run. For extra information I suggest looking into these cases. Here are 2 of the most recent output.logs related to this taking place.
[error.log](https://github.com/Some-Bunny/Planetside/files/14113086/error.log)
[LogOutput.log](https://github.com/Some-Bunny/Planetside/files/14113087/LogOutput.log)

**Comment by Some-Bunny** [comment]
should be fixed as of today
