### ISSUE TITLE
Adding an option to turn of the weapon ammo tweak

### ISSUE THREAD

**Issue by norakum** [Some-Bunny/Planetside#8]
Hello (sorry i'm new, dont know if it's the good place)

I'm playing with Planetside of Gunymede, Expand The Gungeon, Once More Into The Breach and more

The issue is, Expand The Gungeon add "Bootleg" weapon that explode when they reach 0 ammo, and I'm playing with the Shade (a charactere with only 1hp) with OMITB, but the ammo tweak that add Planetside Of Gunymede where gun doesn't have sometime the max ammo when you pick them up, with sometime 0 ammo on it, has made me lose when I grabbed a bootleg pistol, since when i picked it up, it has exploded because he didn't have ammo on it

Is it possible to add an option to disable this tweak, or at least make it not working on the Bootleg gun from Expand The Gungeon?

Thanks a lot!

**Comment by Some-Bunny** [comment]
This is a feature of Ouroborous Mode intended as a slight difficulty modifier. This probably will not get changed, you might just have to avoid picking up bootleg weapons. Sorry

**Comment by Some-Bunny** [comment]
Closing the issue here, also, after checking the code for it, unless I'm mistaken by my own code, the ammo removal effect from Ouroborous is not even able to remove all the ammo from a gun, maxing out at 87.5% of the ammo being removed.

**Comment by norakum** [comment]
> Closing the issue here, also, after checking the code for it, unless I'm mistaken by my own code, the ammo removal effect from Ouroborous is not even able to remove all the ammo from a gun, maxing out at 87.5% of the ammo being removed.

Sorry to reply as the case is closed, but there must be something wrong with the code yes as you can see here : 

https://github.com/Some-Bunny/Planetside/assets/26091841/22d4fedb-5eff-4f15-9f8e-f22cd215eda4

But if you don't want to add an option to remove this not a big deal, i just won't use the bootleg weapon
