### ISSUE TITLE
Visual & gameplay issues related to running on Linux

### ISSUE THREAD

**Issue by Lordfortress** [Some-Bunny/Planetside#9]
![20240421_195604 (1)](https://github.com/Some-Bunny/Planetside/assets/69479977/cf1cad55-c582-42d8-b6ce-75529f76efe5)
![20240421_195604 (3)](https://github.com/Some-Bunny/Planetside/assets/69479977/8476559a-6fbd-4038-9a79-29cc45333a34)
Also pink square enemies and bosses. In general many broken textures. Also uroboros mode just not existing.

All issues that started occurring when I swapped over to Linux native instead of proton. All these issues also exist for Modular character when it's able to even load in. And seems to be the case for all Linux users, don't have an output.log since this has been a while ago but thought it should still be officially reported to the issues list.

Based on talk in the discord it's related to shaderlibs and something with OPENGL.

**Comment by Some-Bunny** [comment]
wontfix for now until i care enough to do something significant enough with Planetside

**Comment by Some-Bunny** [comment]
should be fixed now thanks to pretzel
